# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x1f\n\x10\x43\x61meraAddRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"@\n\x11\x43\x61meraAddResponse\x12\x0e\n\x06src_id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"%\n\x13\x43\x61meraRemoveRequest\x12\x0e\n\x06src_id\x18\x01 \x01(\x05\"6\n\x14\x43\x61meraRemoveResponse\x12\x0e\n\x06src_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x13\n\x11\x43\x61meraListRequest\")\n\nCameraInfo\x12\x0e\n\x06src_id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\"9\n\x12\x43\x61meraListResponse\x12#\n\x07\x63\x61meras\x18\x01 \x03(\x0b\x32\x12.camera.CameraInfo2\xe2\x01\n\rCameraService\x12@\n\tAddCamera\x12\x18.camera.CameraAddRequest\x1a\x19.camera.CameraAddResponse\x12I\n\x0cRemoveCamera\x12\x1b.camera.CameraRemoveRequest\x1a\x1c.camera.CameraRemoveResponse\x12\x44\n\x0bListCameras\x12\x19.camera.CameraListRequest\x1a\x1a.camera.CameraListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAADDREQUEST']._serialized_start=24
  _globals['_CAMERAADDREQUEST']._serialized_end=55
  _globals['_CAMERAADDRESPONSE']._serialized_start=57
  _globals['_CAMERAADDRESPONSE']._serialized_end=121
  _globals['_CAMERAREMOVEREQUEST']._serialized_start=123
  _globals['_CAMERAREMOVEREQUEST']._serialized_end=160
  _globals['_CAMERAREMOVERESPONSE']._serialized_start=162
  _globals['_CAMERAREMOVERESPONSE']._serialized_end=216
  _globals['_CAMERALISTREQUEST']._serialized_start=218
  _globals['_CAMERALISTREQUEST']._serialized_end=237
  _globals['_CAMERAINFO']._serialized_start=239
  _globals['_CAMERAINFO']._serialized_end=280
  _globals['_CAMERALISTRESPONSE']._serialized_start=282
  _globals['_CAMERALISTRESPONSE']._serialized_end=339
  _globals['_CAMERASERVICE']._serialized_start=342
  _globals['_CAMERASERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
