# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import camera_pb2 as camera__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraServiceStub:
    """Dịch vụ quản lý camera động cho DeepStream C++ Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCamera = channel.unary_unary(
                '/camera.CameraService/AddCamera',
                request_serializer=camera__pb2.CameraAddRequest.SerializeToString,
                response_deserializer=camera__pb2.CameraAddResponse.FromString,
                _registered_method=True)
        self.RemoveCamera = channel.unary_unary(
                '/camera.CameraService/RemoveCamera',
                request_serializer=camera__pb2.CameraRemoveRequest.SerializeToString,
                response_deserializer=camera__pb2.CameraRemoveResponse.FromString,
                _registered_method=True)
        self.ListCameras = channel.unary_unary(
                '/camera.CameraService/ListCameras',
                request_serializer=camera__pb2.CameraListRequest.SerializeToString,
                response_deserializer=camera__pb2.CameraListResponse.FromString,
                _registered_method=True)


class CameraServiceServicer:
    """Dịch vụ quản lý camera động cho DeepStream C++ Service
    """

    def AddCamera(self, request, context):
        """Thêm camera RTSP mới vào pipeline đang chạy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCamera(self, request, context):
        """Xóa camera khỏi pipeline bằng ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCameras(self, request, context):
        """Liệt kê danh sách các camera đang active
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCamera,
                    request_deserializer=camera__pb2.CameraAddRequest.FromString,
                    response_serializer=camera__pb2.CameraAddResponse.SerializeToString,
            ),
            'RemoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCamera,
                    request_deserializer=camera__pb2.CameraRemoveRequest.FromString,
                    response_serializer=camera__pb2.CameraRemoveResponse.SerializeToString,
            ),
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=camera__pb2.CameraListRequest.FromString,
                    response_serializer=camera__pb2.CameraListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'camera.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('camera.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService:
    """Dịch vụ quản lý camera động cho DeepStream C++ Service
    """

    @staticmethod
    def AddCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/AddCamera',
            camera__pb2.CameraAddRequest.SerializeToString,
            camera__pb2.CameraAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/RemoveCamera',
            camera__pb2.CameraRemoveRequest.SerializeToString,
            camera__pb2.CameraRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/ListCameras',
            camera__pb2.CameraListRequest.SerializeToString,
            camera__pb2.CameraListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
